package 
{
    import mx.resources.ResourceBundle;

    public class en_US$iLabels_properties extends ResourceBundle 
    {

        public function en_US$iLabels_properties()
        {
            super("en_US", "iLabels");
        }

        override protected function getContent():Object
        {
            var _local1:Object = {
                btnAssumeLabel:"Apply",
				btnBgImage:"Background Image",
                help3_footer:"Please follow step 4. Finish your plan.",
                savePlan_errorHeader:"Saving failed!",
                error_fromEmail_invalid:"Please enter a valid 'From (e-mail)' - address!",
                sendPlan_toEmail:"To (e-mail)",
                loadPlan_errorHeader:"Loading error!",
                btnSendViaEmail:"Send plan by e-mail",
                label_window:"Window",
                help4_2_3_text:"With your iPad:",
                help1_3_3_text:"Align to grid:",
                help2_1_1_text:"Add windows and doors",
                help0_footer:"Please follow step 1. Create room.",
                info_polypex_header:"Bade und Duschwannen",
                form_country:"Country",
                help1_4_2_text:"Tap the selected wall surface at the desired position twice to add a further point for changing the floor plan.",
                getQuote_radius:"Radius (vicinity)",
                btnAngebot:"Invite offers",
                roomMaxPoints:"Maximum number of points achieved ({0})",
                sendPlan_message:"Your message",
                getQuote_radiusSearch:"Select a country and enter a zip code to get a list of partner craftsmen in your area. Leave the box 'code' empty if you want to see all partner craftsmen in the country.",
                country_at:"Austria",
                form_salutation:"Title",
                help0_1_text:"Welcome to Game Builder – your helpful guide to the professional planning of your game.",
                alert_base_form_header:"ATTENTION!",
                help3_1_1_text:"Place article",
                help2_header:"Step 2",
                error_fromName_required:"The field 'from (name)' is a mandatory field!",
                help4_2_4_text_android:"The plan is stored in your document folder. Connect your Android-tablet as hard disk to your computer. Choose the developed plan and save it in any directory in order to load this file into the online bathroom planner and to be able to process it. Vice versa you can save your plan which was created in the online bathroom planner in the document folder of your Android-Tablet and save it as well continue editing in the Bathplanner PRO-App.",
                decimalSeparator:".",
                btnSearchLabel:"Search",
                help3_2_4_text:'Select the symbol "45 degrees" to rotate items in 45 degree increments (2).',
                getQuote_note:"Note",
                error_resellerRequired:"Please choose a desired craftsman!",
                help1_1_2_text:"Select your preferred basic form. As a basis there are three basic forms.",
                getQuote_errorHeader:"Sending error!",
                help4_1_1_text:"Finish your plan",
                help1_2_1_text:'You can create the desired room shape by the dimensions of the pages in the provided input fields and confirm with "Apply". ',
                form_lastname:"Lastname",
                btnYesLabel:"Yes",
                error_form_header:"Error in the form",
                form_firstname:"Firstname",
                help4_2_4_text:'Connect your iPad with iTunes. Now select the app "Bathplanner PRO" and mark the desired plan in the document field. Save your developed plan in any directory in order to upload and process this file in the online bathroom planner. Vice versa you may upload a plan drawn up in the online bathroom planner into your iTunes and after synchronization load and continue editing in your Bathplanner app too.',
                help1_3_4_text:'To align the corners of the room in five-centimetre increments, select the icon "Align to grid". To disable this feature, tap the icon again.',
                info_palme_text2:"Neue Glasdesigns, moderne Beschläge und innovative Griff-Lösungen verbinden sich zu umfassenden Produktfamilien mit faszinierenden Details, geeignet für Duschtassen in allen marktüblichen Formen. Auf Wunsch liefert PALME auch Sonderanfertigungen. Zum umfassenden Markenplus zählen auch Benutzerfreundlichkeit, einfache Pflege und eine lange Lebensdauer. Eben PALME-Qualität ohne Abstriche.\n\nPALME Duschabtrennungen\nJechtenham 16\nA - 4775 Taufkirchen/Pram\nTel. +43 7719 85 85-0\nFax +43 7719 88 73\n\nE-Mail: palme@palme.eu\nHomepage: www.palme.eu\n",
                info_palme_text1:"Hohe Funktionalität und klares Design zeichnen PALME Duschabtrennungen aus.",
                sendPlan_fromName:"From (name)",
                help2_1_2_text:"Now, insert doors and windows in the room marker. Just drag the icon from the selection bar at the left to the grey-bordered space limitation on the plan, symbolizing the masonry. Tap to the inserted icon in order to move it, to scale it, to mirror or delete it.",
                newPlanName:"New Game",
                btnCancelLabel:"Cancel",
                help1_4_3_text:'By holding the point for about two seconds, you may delete a point with the result that the icon for "Clear" appears.',
                sendPlan_successHeader:"Plan sent!",
                help1_footer:"Please follow step 2. Add windows and doors.",
                label_room_reflection:"Mirror room",
                btnSaveAsLabel:"Save as",
                getQuote_reseller_list:"List of dealers",
                error_invalidEmail:"Please enter a valid e-mail - address!",
                label_step4:"4. Finish your game",
                label_step3:"3. Modify behavior",
                label_step2:"2. Add models",
                label_step1:"1. Game Setup",
                help0_2_text:"Benefit from the extensive experience of two leading brands of Sanitary Industry: POLYPEX, the inventor of bath and shower trays made from Polypex, and PALME, an upmarket manufacturer for particularly high-quality shower enclosures.\nTo make your entry as easy as possible we have compiled a small user manual (tutorial) in order to help with the first usage of the apps and guiding you through the various functions. Thus you can plan quickly and easily in four simple steps.\nYour new dream bathroom. Try it, you'll see, it's really easy!\n\nAnd even if you still don't manage, you can access the tutorial at any time again by tapping the top right of the small \"question mark\".\n\nGo for it and we hope you'll enjoy planning your new bathroom,\nPOLYPEX and PALME",
                label_door:"Door",
                help3_1_2_text:"Now select articles and drag them to the prepared plan. You can view all selected articles, move and rotate them exactly where you want to place them.",
                sendPlan_successMessage:"The plan has been successfully sent!",
                form_street:"Street",
                help3_2_1_text:"Hint:",
                help3_header:"Step 3",
                savePlan_errorMessage:"Plan could not be saved!",
                form_zip:"ZIP",
                help3_2_5_text:"Full screen mode:",
                getQuote_errorMessage:"Error during sending the quotation request! Check the internet connection!",
                help1_1_3_text:"If desired, these basic forms can of course be edited and changed at any time.",
                help4_1_2_text:"Send your bathroom plan to friends and acquaintances or pick up an offer for implementation via e-mail. Choose from our list of dealers a partner you trust.",
                getQuote_customReseller_message:"Tell us your own desired craftsman here.",
                help0_header:"Game Builder – Help",
                help1_2_2_text:'To change the basic shape again select "Return to base."',
                sendPlan_errorHeader:"Error in sending!",
                help4_2_1_text:"Save or load:",
                form_email:"E-mail",
                help1_3_1_text:"Mirror space:",
                getQuote_customReseller_header:"Your ideal craftsman is not listed?",
                salutation_female:"Ms",
                getQuote_header:"{0} / 2 get offer",
                sendPlan_info:"Here you can share your plan with friends and acquaintances. The plan is sent in form of an image. Optionally, you can write a message.",
                label_base_form:"Select basic form",
                getQuote_confirm_info:"I agree that my data are only forwarded to selected trading partners. They can contact you by e-mail or, if specified, by telephone.",
                loadPlan_errorMessage:"The file could not be loaded! The file may be damaged.",
                btnSaveLabel:"Save",
                btnDeleteLabel:"Delete",
                btnResetToBaseRoomLabel:"Back to the basic form",
                btnOkLabel:"Ok",
                sendPlan_fromEmail:"From (e-mail)",
                form_city:"City",
                alert_base_form_text:"If you change the basic form all articles, windows and doors are deleted! Do you want to change basic form anyway?",
                btnNoLabel:"No",
                sendPlan_header:"Send plan by e-mail",
                planName:"Plan name",
                help3_2_2_text:'Click the icon "Align to grid" (1). It allows you a simple and exact placement of the article at the wall.',
                savePlan_info:"Save your completed plan for future use. You can open the stored plan online in the bathroom planner.",
                getQuote_reseller:"Dealer",
                help2_footer:"Please follow Step 3. Place article.",
                system_save_successful:"Plan has been saved successfully!",
                help3_2_6_text:"To view your plan in full screen mode, select the appropriate icon (3) Tap the icon again to redisplay the menu structure. ",
                btnLoadLabel:"Load",
                planFileName:"File name",
                help4_header:"Step 4",
                btnSendLabel:"Send",
                help1_1_4_text:"Just drag the end points of the sides to the desired position. This allows wall lengths and thus spaces be increased or decreased. ",
                sendPlan_toName:"To (name)",
                help4_2_3_text_android:"With your Android Tablet:",
                form_company:"Company",
                help1_2_3_text:"PLEASE NOTE: If you have already placed doors, windows and articles, these are also discarded!",
                sendPlan_errorMessage:"While sending the plan an error occurred! Check the Internet connection!",
                savePlan_header:"Save plan",
                help4_2_2_text:"Allows you to save your completed plan or reload a previously stored one. You also have the opportunity to load and edit already created plans of the Bathplanner PRO-App into the online bathroom planner at onlineBathplanner.at. Vice versa you may load and edit already created plans into the Bathplanner PRO-App too.",
                help1_header:"Step 1",
                help1_3_2_text:'Using the symbols "space mirror", you can mirror the basic shape horizontally and vertically.',
                getQuote_reseller_load:"is loading",
                getQuote_reseller_load_error702:"Search of dealer requires an internet connection! Please check whether there is a connection!",
                help1_4_1_text:"Change layout:",
                info_palme_header:"Duschabtrennungen",
                getQuote_reseller_load_error701:"With the current settings a dealer could not be found!",
                getQuote_reseller_load_error700:"Zip code could not be found!",
                error_requiredField:"Field '{0}' is a required field!",
                getQuote_intro:"You have designed the bathroom plan and are now interested in a binding offer? Give us your data and select the desired craftsman. We send your bathroom plan to the selected partner craftsman who in return will get in contact with you in the next few days.",
                form_phone:"Telephone",
                getQuote_successHeader:"Quotation request was sent!",
                error_toEmail_invalid:"Please enter a valid 'To (e-mail)' - address!",
                error_confirmRequired:"Please agree to the consent form!",
                btnNewPlanLabel:"New Level",
                error:"productDetail=Product information cannot be loaded! Please check if an internet connection is available!",
                error_toName_required:"The field 'to (name)' is a mandatory field!",
                getQuote_custom_partner:"Your ideal craftsman is not listed? Tell us your own desired craftsman.",
                info_polypex_text2:"Im umfangreichen Programm finden Sie über 100 Modelle in vielen Sanitärfarben. Diese hochwertigen Bade- und Duschwannen aus POLYPEX sind in Formstabilität, Farb- und Glanztreue sowie Pflegeleichtigkeit weltweit unübertroffen. Die langjährige Erfahrung des Erfinders spiegelt sich in höchster Qualität und zahlreichen Auszeichnungen, wie dem Austria Gütezeichen, wider.\n\nPOLYPEX Wiro Kunststoff-\nFabrik GmbH & CoKG\nA - 4600 Wels, Linzerstraße 246\nTel. +43 7242 43 0 57\nFax +43 7242 60 213\n\nE-Mail: info@polypex.at\nHomepage: www.polypex.at",
                info_polypex_text1:"POLYPEX - Wannen-Qualität aus Österreich setzt seit 4 Jahrzehnten mit seinen Raum- und Problemlösungen Maßstäbe in der Bäderwelt.",
                getQuote_reseller_load_error701_short:"No dealer found!",
                salutation_male:"Mr",
                getQuote_successMessage:"Your quotation request has been sent successfully!",
                btnResumeLabel:"Next",
                getQuote_reseller_load_error702_short:"No internet connection!",
                country_de:"Germany",
                help3_2_3_text:"45 degree rotation:",
                label_base_measure:"Enter basic dimensions",
                help1_1_1_text:"Setup Game",
                getQuote_start:"Start of construction",
				appLabel:"Game Studio"
            };
            return (_local1);
        }


    }
}//package 
